node:
  build: .
  dockerfile: node.dockerfile
  command: bash -c "npm i && ./node_modules/knex/lib/bin/cli.js migrate:latest && npm start"
  volumes:
    - .:/app
    - /app/node_modules
  ports:
    - "8000:8000"
  links:
    - db
db:
  image: postgres
  restart: always
  environment:
    POSTGRES_DB: testdb
